services:
  ms-go-validation-orchestrator:
    container_name: ms-go-validation-orchestrator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-8080}
      SERVICE_NAME: ${SERVICE_NAME:-ms-go-validation-orchestrator}
      HTML_VALIDATOR_URL: ${HTML_VALIDATOR_URL:-}
      CSS_VALIDATOR_URL: ${CSS_VALIDATOR_URL:-}
      REACT_VALIDATOR_URL: ${REACT_VALIDATOR_URL:-}
      NODE_VALIDATOR_URL: ${NODE_VALIDATOR_URL:-}
      PHP_VALIDATOR_URL: ${PHP_VALIDATOR_URL:-}
      PHP_FRAMEWORK_VALIDATOR_URL: ${PHP_FRAMEWORK_VALIDATOR_URL:-}
      NEXTJS_VALIDATOR_URL: ${NEXTJS_VALIDATOR_URL:-}
      BROWSER_RUNTIME_VALIDATOR_URL: ${BROWSER_RUNTIME_VALIDATOR_URL:-}
      GIT_VALIDATOR_URL: ${GIT_VALIDATOR_URL:-}
      DOCKER_VALIDATOR_URL: ${DOCKER_VALIDATOR_URL:-}
      PYTHON_VALIDATOR_URL: ${PYTHON_VALIDATOR_URL:-}
      GO_CODE_VALIDATOR_URL: ${GO_CODE_VALIDATOR_URL:-}
      DB_VALIDATOR_URL: ${DB_VALIDATOR_URL:-}
      LINUX_VALIDATOR_URL: ${LINUX_VALIDATOR_URL:-}
      CACHE_SEARCH_VALIDATOR_URL: ${CACHE_SEARCH_VALIDATOR_URL:-}
      HTTP_RUNTIME_VALIDATOR_URL: ${HTTP_RUNTIME_VALIDATOR_URL:-}
    restart: unless-stopped
    networks:
      - default
      - ms-net

networks:
  ms-net:
    external: true
